services:
  my-server:
    build: .
#    ports:
#      - 8080:8080
#    depends_on:
#      mysql:
#        condition: service_healthy
#      redis:
#        condition: service_healthy

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trade
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD","mysqladmin","ping"]
      interval: 5s
      retries : 10

  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      retries : 10